version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_DEBUG=false
      - APP_ENV=production
      - APP_URL=http://shoutzor.local:8000
      - MIX_PUSHER_APP_KEY=
      - MIX_PUSHER_SOCKET_HOST=
      - MIX_PUSHER_PORT=443
      - MIX_PUSHER_SCHEME=https
