name: Build
on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]
jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Frontend
        uses: docker/build-push-action@v3
        with:
          file: './.Dockerfile'
          push: true
          tags: xorinzor/shoutz0r-frontend:latest
      -